tcp :
  services :
    nas :
      loadBalancer :
        servers :
           - address : "192.168.1.250:443"

  routers :
    nas :
      entryPoints : 
        - "websecure"
      rule : "HostSNI(`telechargement.cicorella.net`) || HostSNI(`audio.cicorella.net`) || HostSNI(`nas.cicorella.net`) || HostSNI(`video.cicorella.net`) || HostSNI(`drive.cicorella.net`) || HostSNI(`photo.cicorella.net`) || HostSNI(`file.cicorella.net`)"
      service : nas
      tls:
        passthrough: true

