version: '3'

services:
  minio:
    image: quay.io/minio/minio
    deploy :
      labels:
        - "traefik.enable=true"
        - "traefik.http.middlewares.minio-gzip.compress=true"

        - "traefik.http.routers.minio-https.entrypoints=websecure"
        - "traefik.http.routers.minio-https.tls=true"
        - "traefik.http.routers.minio-https.tls.certresolver=le"
        - "traefik.http.routers.minio-https.middlewares=minio-gzip"
        - "traefik.http.routers.minio-https.rule=Host(`minio.cluster.cicorella.net`)"
        - "traefik.http.routers.minio-https.service=minio-backend"

        - "traefik.http.routers.minio-admin.entrypoints=websecure"
        - "traefik.http.routers.minio-admin.tls=true"
        - "traefik.http.routers.minio-admin.tls.certresolver=le"
        - "traefik.http.routers.minio-admin.middlewares=minio-gzip"
        - "traefik.http.routers.minio-admin.rule=Host(`minio-admin.cluster.cicorella.net`)"
        - "traefik.http.routers.minio-admin.service=minio-admin-backend"

        - "traefik.http.services.minio-backend.loadbalancer.server.scheme=http"
        - "traefik.http.services.minio-backend.loadbalancer.server.port=9000"

        - "traefik.http.services.minio-admin-backend.loadbalancer.server.scheme=http"
        - "traefik.http.services.minio-admin-backend.loadbalancer.server.port=9001"
    environment:
      - MINIO_ROOT_USER=${NINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_DOMAIN=minio.cluster.cicorella.net
      - MINIO_SERVER_URL=https://minio.cluster.cicorella.net 
      - MINIO_BROWSER=on
      - MINIO_BROWSER_REDIRECT_URL=https://minio-admin.cluster.cicorella.net
    command: minio server /data --console-address 0.0.0.0:9001
    networks:
      - traefik-public
    volumes:
      - cifs_mount:/data


networks:
  traefik-public:
    external: true
volumes:
  cifs_mount:
    driver: local
    driver_opts:
      type: cifs    
      device: //192.168.100.250/services/swarmTest/minio/data
      o: "username=docker,password=SwarmCluster123456,vers=3.0,uid=1000,gid=1000,mfsymlinks"


